### ISSUE TITLE
[QUILT] Crash Mod Incompatibilities 

### ISSUE THREAD

**Issue by greensad** [lucaargolo/kibe#188]
Game crashes using a base configuration. These mods crash when applied together:

'Kibe 1.19.10 BETA'
'Fabric Language Kotlin 1.8.7 kotlin 1.7.22'
'Quilted Fabric API 4.0.0 beta24 0.68.0'

'Charm 4.4.4' or 'Effective 1.4' or 'Oh The Biomes You'll Go 2.0.0.13'

Log: https://mclo.gs/l7jpTf2

**Comment by xVanquishx** [comment]
Can confirm that it isn't byg, effective and charm also crashes for me, but charm has a lot of incompatibilities

**Comment by FibreTTP** [comment]
Kibe 1.19.10 BETA and Effective 1.6 do not seem to be crashing for me on Quilt 0.17.8.

Libraries and APIs:
Satin 1.9.0
Quilt Kotlin Libraries 1.0.2
Quilted Fabric API 4.0.0 beta 25 + QSL 0.70.0

---

Kibe 1.19.10 BETA and Charm 4.4.4 are still crashing on startup on Quilt 0.17.8 and Quilt 0.18.1 beta 26. Same error in log as original issue, seems to be Kibe's fault.

Libraries and APIs:
Quilt Kotlin Libraries 1.0.2
Quilted Fabric API 4.0.0 beta 25 + QSL 0.70.0

**Comment by greensad** [comment]
Update for Lucaargolo: Kibe is still crashing on ver 1.9.11

**Comment by lucaargolo** [comment]
Just tested it and it still seems to be an issue, but I don't think its anything to do with this mod since I don't even change anything related to whats crashing. Since it also happens with other unrelated mods, it's probably a quilt/charm issue.
I'll close this but if anyone knows whats actually wrong and it ends up being my fault I can happily reopen it.
