### ISSUE TITLE
Failed to start server

### ISSUE THREAD

**Issue by srnyx** [lucaargolo/kibe#72]
Server crashes when using v1.6.8 and v1.6.9. v1.6.7 works fine.
https://paste.srnyx.xyz/etuvihaviw.pl

**Comment by char1es31** [comment]
I have the issue with:
❌ v1.6.8 and 
❌ v1.6.9 
but not with
✔️ v1.6.7

https://pastebin.com/uP53C8jY

**Comment by lucaargolo** [comment]
Yes, this is known. It happened because when I updated to Kotlin 1.5 it changed how the compile process worked and messed up some classes that were previously working. I'll release version 1.7 in a few days, it will have this fixed, together with a bunch of new features. For now, if you're playing on dedicated servers please keep using 1.6.7.
